### ISSUE TITLE
Requests to localhost are handed to DNS resolver

### ISSUE THREAD

**Issue by andig** [reactphp/http-client#11]
...where they invariably fail.

**Comment by frankmayer** [comment]
Hi there. Is there any solution planned for this? It bit me today :smile:

**Comment by frankmayer** [comment]
This is actually a bigger issue when working with linked containers in Docker.
Explanation:
In Docker, when a link is created from one container to the other, for example from a php container to a db or service container, then the (dynamic) ip & hostname for that target container is written into /etc/hosts, Since the DNS resolver does not honor /etc/hosts, the lookup fails.

**Comment by WyriHaximus** [comment]
There is an issue about this on on the DNS component: https://github.com/reactphp/dns/issues/10

Since I'm also working on the filesystem component we should look into using that to resolve this :+1: /cc @clue

**Comment by frankmayer** [comment]
BTW, I found a temporary workaround using "dnsmasq" and described it in my [blog](http://www.frankmayer.me/blog/14-a-solution-to-use-reactphp-in-docker-with-linked-containers-aka-fixing-the-etc-hosts-problem)

**Comment by itcreator** [comment]
+1 for docker

**Comment by clue** [comment]
Big +1 for getting this in, both for convenience ("localhost" etc.) and for Docker containers!

I've started looking into this a few weeks ago, but have postponed this for now because the DNS component is currently undergoing some major architectural refactorings.

**Comment by Filsh** [comment]
I used it
http://php.net/manual/en/function.gethostbyname.php

**Comment by SamMousa** [comment]
One solution would be to implement a `HostsExecutor` and a `FallthroughExecutor`, combining these you would be able to have proper hosts file functionality, if you want it.
